import type { Article } from "./types"

// Mock data based on the provided JSON
export const articles: Article[] = [
  {
    id: 6,
    documentId: "nu4sk7vq1493kv4709g6htod",
    title: "A bug is becoming a meme on the internet",
    description: "How a bug on MySQL is becoming a meme on the internet",
    slug: "a-bug-is-becoming-a-meme-on-the-internet",
    createdAt: "2025-05-22T15:15:51.607Z",
    updatedAt: "2025-05-22T15:15:51.607Z",
    publishedAt: "2025-05-22T15:38:10.325Z",
    cover: {
      id: 7,
      documentId: "px92qyu2vjhveos9qrecufxo",
      name: "a-bug-is-becoming-a-meme-on-the-internet",
      alternativeText: "An image uploaded to Strapi called a-bug-is-becoming-a-meme-on-the-internet",
      url: "/bug-meme.png",
    },
    category: {
      id: 2,
      documentId: "dz9f3znmxf84ho4dhb8hp59x",
      name: "tech",
      slug: "tech",
    },
    author: {
      id: 2,
      documentId: "dy6mhrdhhk80ueewky13iinz",
      name: "Sarah Baker",
      email: "sarahbaker@strapi.io",
      createdAt: "2025-05-22T15:15:50.827Z",
      updatedAt: "2025-05-22T15:15:50.827Z",
      publishedAt: "2025-05-22T15:15:50.826Z",
      avatar: {
        id: 2,
        documentId: "nldpmjrx9qhcbr3fxhgm00ur",
        url: "/placeholder.svg?height=100&width=100&query=woman profile",
        alternativeText: "An image uploaded to Strapi called sarahbaker@strapi",
        width: 3321,
        height: 2746,
      },
    },
    blocks: [
      {
        __component: "shared.rich-text",
        id: 12,
        body: "## Probant \n\nse Lorem markdownum negat. Argo *saxa* videnda cornuaque hunc qui tanta spes teneas! Obliquis est dicenti est salutat ille tamen iuvenum nostrae dolore. - Colores nocituraque comitata eripiunt - Addit quodcunque solum cui et dextram illis - Nulli meus nec extemplo ille ferebat pressit Se blandita fulvae vox gravem Pittheus cesserunt sanguine herbis tu comitum tenuit. Sui in ruunt; Doridaque maculosae fuissem! Et loqui. \n\n## Abit sua\n\nse Lorem markdownum negat. Argo *saxa* videnda cornuaque hunc qui tanta spes teneas! Obliquis est dicenti est salutat ille tamen iuvenum nostrae dolore. - Colores nocituraque comitata eripiunt - Addit quodcunque solum cui et dextram illis - Nulli meus nec extemplo ille ferebat pressit Se blandita fulvae vox gravem Pittheus cesserunt sanguine herbis tu comitum tenuit. Sui in ruunt; Doridaque maculosae fuissem! Et loqui. ",
      },
      {
        __component: "shared.quote",
        id: 7,
        title: "Thelonius Monk",
        body: "You've got to dig it to dig it, you dig?",
      },
      {
        __component: "shared.media",
        id: 7,
        file: {
          id: 4,
          documentId: "txns1d5tghuzy2a3a9e6z4u3",
          url: "/placeholder.svg?height=600&width=800&query=coffee art",
          alternativeText: "An image uploaded to Strapi called coffee-art",
          width: 5824,
          height: 3259,
        },
      },
      {
        __component: "shared.rich-text",
        id: 13,
        body: "## Spatiantia astra \n\nFoeda, medio silva *errandum*: onus formam munere. Mutata bibulis est auxiliare arces etiamnunc verbis virgineo Priamidas illa Thescelus, nam fit locis lucis auras. Exitus hospes gratulor ut pondere [speslimite](http://www.curas.io/figuram); quid habent, Avernales faciente de. Pervenit Ino sonabile supplex cognoscenti vires, Bacchumque errat miserarum venandi dignabere dedisti. Discrimina iuncosaque virgaque tot sine superest [fissus](http://quos.org/sitet.aspx). Non color esset potest non sumit, sed vix arserat. Nisi immo silva tantum pectusque quos pennis quisquam artus!",
      },
      {
        __component: "shared.slider",
        id: 6,
        files: [
          {
            id: 4,
            documentId: "txns1d5tghuzy2a3a9e6z4u3",
            name: "coffee-art",
            url: "/placeholder.svg?height=600&width=800&query=coffee art",
            alternativeText: "An image uploaded to Strapi called coffee-art",
          },
          {
            id: 5,
            documentId: "uw9dh9i74byvmzlzd7qcgvhg",
            name: "coffee-beans",
            url: "/placeholder.svg?height=600&width=800&query=coffee beans",
            alternativeText: "An image uploaded to Strapi called coffee-beans",
          },
        ],
      },
    ],
  },
  {
    id: 7,
    documentId: "zler8wiz0ww7u3c6r0imtj13",
    title: "Beautiful picture",
    description: "Description of a beautiful picture",
    slug: "beautiful-picture",
    createdAt: "2025-05-22T15:15:51.725Z",
    updatedAt: "2025-05-22T15:15:51.725Z",
    publishedAt: "2025-05-22T15:38:10.325Z",
    cover: {
      id: 8,
      documentId: "sz85lu4h9026wdzx2ee5w6js",
      name: "beautiful-picture",
      alternativeText: "An image uploaded to Strapi called beautiful-picture",
      url: "/placeholder.svg?height=600&width=800&query=beautiful landscape",
    },
    category: {
      id: 4,
      documentId: "gkyduoob2f5kpi0yhtb2edw1",
      name: "nature",
      slug: "nature",
    },
    author: {
      id: 2,
      documentId: "dy6mhrdhhk80ueewky13iinz",
      name: "Sarah Baker",
      email: "sarahbaker@strapi.io",
      createdAt: "2025-05-22T15:15:50.827Z",
      updatedAt: "2025-05-22T15:15:50.827Z",
      publishedAt: "2025-05-22T15:15:50.826Z",
      avatar: {
        id: 2,
        documentId: "nldpmjrx9qhcbr3fxhgm00ur",
        url: "/placeholder.svg?height=100&width=100&query=woman profile",
        alternativeText: "An image uploaded to Strapi called sarahbaker@strapi",
        width: 3321,
        height: 2746,
      },
    },
    blocks: [
      {
        __component: "shared.rich-text",
        id: 14,
        body: "## Probant \n\nse Lorem markdownum negat. Argo *saxa* videnda cornuaque hunc qui tanta spes teneas! Obliquis est dicenti est salutat ille tamen iuvenum nostrae dolore. - Colores nocituraque comitata eripiunt - Addit quodcunque solum cui et dextram illis - Nulli meus nec extemplo ille ferebat pressit Se blandita fulvae vox gravem Pittheus cesserunt sanguine herbis tu comitum tenuit. Sui in ruunt; Doridaque maculosae fuissem! Et loqui. \n\n## Abit sua\n\nse Lorem markdownum negat. Argo *saxa* videnda cornuaque hunc qui tanta spes teneas! Obliquis est dicenti est salutat ille tamen iuvenum nostrae dolore. - Colores nocituraque comitata eripiunt - Addit quodcunque solum cui et dextram illis - Nulli meus nec extemplo ille ferebat pressit Se blandita fulvae vox gravem Pittheus cesserunt sanguine herbis tu comitum tenuit. Sui in ruunt; Doridaque maculosae fuissem! Et loqui. ",
      },
      {
        __component: "shared.quote",
        id: 8,
        title: "Thelonius Monk",
        body: "You've got to dig it to dig it, you dig?",
      },
      {
        __component: "shared.media",
        id: 8,
        file: {
          id: 4,
          documentId: "txns1d5tghuzy2a3a9e6z4u3",
          url: "/placeholder.svg?height=600&width=800&query=coffee art",
          alternativeText: "An image uploaded to Strapi called coffee-art",
          width: 5824,
          height: 3259,
        },
      },
    ],
  },
  {
    id: 8,
    documentId: "zl8l5jonrjbgb39npeoc8982",
    title: "The internet's Own boy",
    description: "Follow the story of Aaron Swartz, the boy who could change the world",
    slug: "the-internet-s-own-boy",
    createdAt: "2025-05-22T15:15:51.472Z",
    updatedAt: "2025-05-22T15:15:51.472Z",
    publishedAt: "2025-05-22T15:38:10.325Z",
    cover: {
      id: 3,
      documentId: "j3ds729hhmouf3e2eenb8a38",
      name: "the-internet-s-own-boy",
      alternativeText: "An image uploaded to Strapi called the-internet-s-own-boy",
      url: "/placeholder.svg?height=600&width=800&query=aaron swartz",
    },
    category: {
      id: 5,
      documentId: "c76s6xexmotztnp6t4o4gr6d",
      name: "story",
      slug: "story",
    },
    author: {
      id: 1,
      documentId: "icaj7yshzlk4styr8yd2bu3v",
      name: "David Doe",
      email: "daviddoe@strapi.io",
      createdAt: "2025-05-22T15:15:50.712Z",
      updatedAt: "2025-05-22T15:15:50.712Z",
      publishedAt: "2025-05-22T15:15:50.712Z",
      avatar: {
        id: 1,
        documentId: "q1fu20vjt7urq0ljy1avx8oo",
        url: "/placeholder.svg?height=100&width=100&query=man profile",
        alternativeText: "An image uploaded to Strapi called daviddoe@strapi",
        width: 2418,
        height: 2711,
      },
    },
    blocks: [
      {
        __component: "shared.rich-text",
        id: 16,
        body: "## Probant \n\nse Lorem markdownum negat. Argo *saxa* videnda cornuaque hunc qui tanta spes teneas! Obliquis est dicenti est salutat ille tamen iuvenum nostrae dolore. - Colores nocituraque comitata eripiunt - Addit quodcunque solum cui et dextram illis - Nulli meus nec extemplo ille ferebat pressit Se blandita fulvae vox gravem Pittheus cesserunt sanguine herbis tu comitum tenuit. Sui in ruunt; Doridaque maculosae fuissem! Et loqui. \n\n## Abit sua\n\nse Lorem markdownum negat. Argo *saxa* videnda cornuaque hunc qui tanta spes teneas! Obliquis est dicenti est salutat ille tamen iuvenum nostrae dolore. - Colores nocituraque comitata eripiunt - Addit quodcunque solum cui et dextram illis - Nulli meus nec extemplo ille ferebat pressit Se blandita fulvae vox gravem Pittheus cesserunt sanguine herbis tu comitum tenuit. Sui in ruunt; Doridaque maculosae fuissem! Et loqui. ",
      },
      {
        __component: "shared.quote",
        id: 9,
        title: "Thelonius Monk",
        body: "You've got to dig it to dig it, you dig?",
      },
    ],
  },
  {
    id: 9,
    documentId: "o32fisv3vfb73sx6z1gf89n2",
    title: "This shrimp is awesome",
    description: "Mantis shrimps, or stomatopods, are marine crustaceans of the order Stomatopoda.",
    slug: "this-shrimp-is-awesome",
    createdAt: "2025-05-22T15:15:51.507Z",
    updatedAt: "2025-05-22T15:15:51.507Z",
    publishedAt: "2025-05-22T15:38:10.325Z",
    cover: {
      id: 6,
      documentId: "pevvt94mgc2t5s9o5sawr64u",
      name: "this-shrimp-is-awesome",
      alternativeText: "An image uploaded to Strapi called this-shrimp-is-awesome",
      url: "/placeholder.svg?height=600&width=800&query=mantis shrimp",
    },
    category: {
      id: 4,
      documentId: "gkyduoob2f5kpi0yhtb2edw1",
      name: "nature",
      slug: "nature",
    },
    author: {
      id: 1,
      documentId: "icaj7yshzlk4styr8yd2bu3v",
      name: "David Doe",
      email: "daviddoe@strapi.io",
      createdAt: "2025-05-22T15:15:50.712Z",
      updatedAt: "2025-05-22T15:15:50.712Z",
      publishedAt: "2025-05-22T15:15:50.712Z",
      avatar: {
        id: 1,
        documentId: "q1fu20vjt7urq0ljy1avx8oo",
        url: "/placeholder.svg?height=100&width=100&query=man profile",
        alternativeText: "An image uploaded to Strapi called daviddoe@strapi",
        width: 2418,
        height: 2711,
      },
    },
    blocks: [
      {
        __component: "shared.rich-text",
        id: 18,
        body: "## Probant \n\nse Lorem markdownum negat. Argo *saxa* videnda cornuaque hunc qui tanta spes teneas! Obliquis est dicenti est salutat ille tamen iuvenum nostrae dolore. - Colores nocituraque comitata eripiunt - Addit quodcunque solum cui et dextram illis - Nulli meus nec extemplo ille ferebat pressit Se blandita fulvae vox gravem Pittheus cesserunt sanguine herbis tu comitum tenuit. Sui in ruunt; Doridaque maculosae fuissem! Et loqui. \n\n## Abit sua\n\nse Lorem markdownum negat. Argo *saxa* videnda cornuaque hunc qui tanta spes teneas! Obliquis est dicenti est salutat ille tamen iuvenum nostrae dolore. - Colores nocituraque comitata eripiunt - Addit quodcunque solum cui et dextram illis - Nulli meus nec extemplo ille ferebat pressit Se blandita fulvae vox gravem Pittheus cesserunt sanguine herbis tu comitum tenuit. Sui in ruunt; Doridaque maculosae fuissem! Et loqui. ",
      },
    ],
  },
  {
    id: 10,
    documentId: "hlmkkyk0qf2iglozvt45k8fj",
    title: "What's inside a Black Hole",
    description: "Maybe the answer is in this article, or not...",
    slug: "what-s-inside-a-black-hole",
    createdAt: "2025-05-22T15:15:51.752Z",
    updatedAt: "2025-05-22T15:15:51.752Z",
    publishedAt: "2025-05-22T15:38:10.325Z",
    cover: {
      id: 9,
      documentId: "whzdvtwwj0tf7qukxt5mm7wk",
      name: "what-s-inside-a-black-hole",
      alternativeText: "An image uploaded to Strapi called what-s-inside-a-black-hole",
      url: "/placeholder.svg?height=600&width=800&query=black hole",
    },
    category: {
      id: 1,
      documentId: "k51uuvna3cqm309csblf56r9",
      name: "news",
      slug: "news",
    },
    author: {
      id: 2,
      documentId: "dy6mhrdhhk80ueewky13iinz",
      name: "Sarah Baker",
      email: "sarahbaker@strapi.io",
      createdAt: "2025-05-22T15:15:50.827Z",
      updatedAt: "2025-05-22T15:15:50.827Z",
      publishedAt: "2025-05-22T15:15:50.826Z",
      avatar: {
        id: 2,
        documentId: "nldpmjrx9qhcbr3fxhgm00ur",
        url: "/placeholder.svg?height=100&width=100&query=woman profile",
        alternativeText: "An image uploaded to Strapi called sarahbaker@strapi",
        width: 3321,
        height: 2746,
      },
    },
    blocks: [
      {
        __component: "shared.rich-text",
        id: 20,
        body: "## Probant \n\nse Lorem markdownum negat. Argo *saxa* videnda cornuaque hunc qui tanta spes teneas! Obliquis est dicenti est salutat ille tamen iuvenum nostrae dolore. - Colores nocituraque comitata eripiunt - Addit quodcunque solum cui et dextram illis - Nulli meus nec extemplo ille ferebat pressit Se blandita fulvae vox gravem Pittheus cesserunt sanguine herbis tu comitum tenuit. Sui in ruunt; Doridaque maculosae fuissem! Et loqui. \n\n## Abit sua\n\nse Lorem markdownum negat. Argo *saxa* videnda cornuaque hunc qui tanta spes teneas! Obliquis est dicenti est salutat ille tamen iuvenum nostrae dolore. - Colores nocituraque comitata eripiunt - Addit quodcunque solum cui et dextram illis - Nulli meus nec extemplo ille ferebat pressit Se blandita fulvae vox gravem Pittheus cesserunt sanguine herbis tu comitum tenuit. Sui in ruunt; Doridaque maculosae fuissem! Et loqui. ",
      },
    ],
  },
]
